apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    version: v1
spec:
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx
      - name: nginx-archive
        persistentVolumeClaim:
          claimName: nginx-archive
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
        - name: nginx-archive
          mountPath: /archive
