apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
    version: v1
spec:
  template:
    metadata:
      labels:
        app: worker
        version: v1
    spec:
      volumes:
      - name: worker-archive
        persistentVolumeClaim:
          claimName: worker-archive
      containers:
      - name: worker
        image: codecov/enterprise:v4.3.9
        env:
        - name: SETUP_ENTERPRISE_LICENSE
          volume: null
        command: [ "/bin/run" ]
        args: [ "worker" ]
        ports:
        - name: http
          containerPort: 5000
        volumeMounts:
        - name: worker-archive
          mountPath: /archive
